### ISSUE TITLE
Stock Bootstrap feel

### ISSUE THREAD

**Issue by cydrobolt** [mozilla/mozilla-badges#37]
This is probably a trivial issue, but the stock Bootstrap feel is a bit annoying. Perhaps we can customize it a little bit :)

**Comment by andrewhayward** [comment]
Hi @Cydrobolt - thanks for raising this point.

Ordinarily I'd suggest adding this issue to [the current Mozilla Badges repo](/mozilla/badges.mozilla.org). However, in this case, given that the purpose of this repository is to do precisely as you suggest, I'll make no such comment :)

Anyway, hold on tight... we intend to have a new site out, with a design overhaul, in a couple of weeks.
